### ISSUE TITLE
Any change introduce lottie version 3.0.0 ?

### ISSUE THREAD

**Issue by ChunChiehHuang18** [xsahil03x/giffy_dialog#100]
**Is your feature request related to a problem? Please describe.**

Hi Since Lottie version 3.0.0 introduce [`renderCache`](https://pub.dev/packages/lottie#performance-or-excessive-cpugpu-usage). Any change introduce new version of lottie in giffy dialog?

**Describe the solution you'd like**
introduct new version of lottie and support  parameters maybe.

**Describe alternatives you've considered**
none

**Additional context**
none

Appreciate this awesome package.

**Comment by xsahil03x** [comment]
Added in [v2.1.0](https://pub.dev/packages/giffy_dialog/changelog#210) 👍🏼

**Comment by ChunChiehHuang18** [comment]
Thanks
