### ISSUE TITLE
'Image' is imported from both 'package

### ISSUE THREAD

**Issue by 88hwany** [xsahil03x/giffy_dialog#110]
Flutter 3.24.1 
giffy_dialog: ^2.1.0

I am getting the following build error:
==> 
../../../../.pub-cache/hosted/pub.dev/giffy_dialog-2.1.0/lib/src/giffy_modal.dart:5:1: Error: 'Image' is imported from both 'package:flutter/src/widgets/image.dart' and 'package:rive/src/rive_core/shapes/image.dart'.
import 'package:rive/rive.dart';
^^^^^
Target kernel_snapshot_program failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildRelease'.
> Process 'command '/Users/lee/ToolKits/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 34s
Running Gradle task 'bundleRelease'...                             34.7s
Gradle task bundleRelease failed with exit code 1

**Comment by alamsyahh15** [comment]
<img width="1118" alt="Screenshot 2024-09-03 at 14 24 56" src="https://github.com/user-attachments/assets/e1936d09-1876-4749-839e-49c483f803ad">

I think this issue in file giffy_modal.dart in line 5, if this package using multiple class Image from rive and material please owner add prefix in rive import like this

`import 'package:rive/rive.dart' as rive ;`

or when this package using load image by rive widget, you can hide Image class is one of the packages
`import 'package:flutter/material.dart' hide Image ;`
or
`import 'package:rive/rive.dart' hide Image ;`
