### ISSUE TITLE
customise the button

### ISSUE THREAD

**Issue by premtemp1** [xsahil03x/giffy_dialog#13]
How can you customize the button...

e.g
change the name,
position the button vertically
Add  new button

**Comment by hkp27299** [comment]
I can help you you can check my some example apps on github.?

**Comment by AmaldevAD** [comment]
i can do that

**Comment by enzoftware** [comment]
The new button is like a third button or convert it into a list of buttons???

**Comment by vish198910** [comment]
I can do this.

**Comment by xsahil03x** [comment]
@vish198910 yes, go on

**Comment by xsahil03x** [comment]
Fixed in https://github.com/xsahil03x/giffy_dialog/releases/tag/v2.0.0
