### ISSUE TITLE
cross-reference

### ISSUE THREAD

**Issue by natezhengbne** [xsahil03x/giffy_dialog#4]
Because every version of giffy_dialog depends on cached_network_image ^0.5.1 which depends on flutter_cache_manager ^0.2.0+1, every version of giffy_dialog requires flutter_cache_manager ^0.2.0+1.
And because flutter_cache_manager >=0.1.0-rc.1 <0.3.0-alpha depends on shared_preferences ^0.4.0, every version of giffy_dialog requires shared_preferences ^0.4.0.
So, because mobile_driver_app depends on both giffy_dialog ^1.2.0 and shared_preferences ^0.5.1+1, version solving failed.

I think the best way is not depend on any network plugin

**Comment by xsahil03x** [comment]
Can you send a PR with the same changes ?

**Comment by Purus** [comment]
If this isn't a major change, I can try fixing this issue.

**Comment by xsahil03x** [comment]
Fixed in #5  closing.
