### ISSUE TITLE
TextAlign doesn't affect the title

### ISSUE THREAD

**Issue by ArtemKolichenkov** [xsahil03x/giffy_dialog#43]
TextAlign for title text doesn't do anything, it can be start or end - nothing changes, it always stays in the center.
I suggest
- either remove it from example (since `textAlign: TextAlign.center,` doesn't affect anything)
- or handle title alignment properly.

**Comment by astralstriker** [comment]
Seems like an issue with `Column`'s `crossAxisAlignment` property. This should be overridable using `Align `widget on the Text (or its parent `Padding `widget) widget but you will need to translate `TextAlign` into `Alignment`.

**Comment by xsahil03x** [comment]
@ArtemKolichenkov this seems like a bug, thanks for pointing this out. I will fix this once I got time meanwhile, you can work on this if you want.
