### ISSUE TITLE
Looking up a deactivated widget's ancestor is unsafe.

### ISSUE THREAD

**Issue by jkjkjk007** [xsahil03x/giffy_dialog#6]
At this point the state of the widget's element tree is no longer stable. To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling inheritFromWidgetOfExactType() in the widget's didChangeDependencies() method.

**Comment by xsahil03x** [comment]
Hey @jkjkjk007 thanks for pointing that out, You can start with this if you want. I am little busy due to office now a days.
