### ISSUE TITLE
Dialog without a button and will be dismiss programmatically

### ISSUE THREAD

**Issue by annagat** [xsahil03x/giffy_dialog#60]
Hello,

I am a newbie. I have already a working code of a buttonless dialog and dismisses programmatically. Until I found this awesome package and I want to replace the dialog with giffy. How could I make a buttonless dialog and make this a function so I can just call in the future builder.

Below is my code for the dialog;
`  showAlertDialog(BuildContext context) {
      AlertDialog alert = AlertDialog(
        title: Text("Slow Internet Connection!"),
        content: Text("Your internet speed connection is too slow. " 
                    "Switch to Airplane mode to continue making transaction."
      ),
    );`

    showDialog(
      barrierDismissible: false,
      context: context,
      builder: (BuildContext context) {
        return alert;
      },
    );
  }`

And I can call this in the builder widget and dismiss using `Navigator.of(context).pop();` on some condition.

How could I implement this using giffy_dialog. Thanks in advance.

**Comment by xsahil03x** [comment]
Hey @annagat Giffy Dialog is an extended version of normal dialog. So it will work similarly to the alert dialog. You don't have to do anything special just call showDialog in your builder and pop it whenever you want, just like you are doing with the alert dialog.

**Comment by annagat** [comment]
Hi @xsahil03x,

Thanks for the response. I was able to make it work.
