### ISSUE TITLE
How cancel button dismisses the dialog?

### ISSUE THREAD

**Issue by Ziyad33** [xsahil03x/giffy_dialog#61]
I use 'Navigator.of(context).pop();' once I get '200' statusCode from the server and immediately show the giffy dialog.

and I have another pop() in the dialog as follow:

```
onOkButtonPressed: () {
            Navigator.of(context).pop();
          },
```

when I press OK, I get the following error:

> I/flutter (14881): Another exception was thrown: Instance of 'DiagnosticsProperty<void>'

am guessing because the screen with the 'context' was already gone, however, when I press cancel, the dialog get dismissed, just how I want it to happen.

my question is, how can I dismiss the dialog when OK is pressed just like the Cancel button?

**Comment by SaadBinShahid** [comment]
anybody solved this? 

```
onOkButtonPressed: () { Navigator.of(context).pop(); },
```

cannot be used like `giffy_dialog-1.6.1/lib/src/base_dialog.dart:206`

```
onPressed: widget.onCancelButtonPressed ?? () => Navigator.of(context).pop(),
```

because the context is different.

Using `Navigator.of(context).pop();` throws the following exception, which makes sense.

```
(2) Exception caught by gesture 

═════════════════════════════════════════════
Looking up a deactivated widget's ancestor is unsafe.
═════════════════════════════════════════════
```

help!

**Comment by SaadBinShahid** [comment]
Pull request added to have cancel button only @ https://github.com/xsahil03x/giffy_dialog/pull/62.

**Comment by Ziyad33** [comment]
thanks, your efforts are appreciated,

I couldn't find the latest update on 'pub.dev' so I added the code manually myself and it is working,

Is it the best way to go about this? because I usually use 'pubspec.yml' and the latest update '1.6.2' isn't available yet.
