### ISSUE TITLE
New Feature: add support for RichText

### ISSUE THREAD

**Issue by edwin-alvarez** [xsahil03x/giffy_dialog#67]
current NetworkGiffyDialog implementation allows:
  final Text title;
  final Text description;

can these be modified to support 
`var text = new RichText(
text: new TextSpan(
  // Note: Styles for TextSpans must be explicitly defined.
  // Child text spans will inherit styles from parent
  style: new TextStyle(
    fontSize: 14.0,
    color: Colors.black,
  ),
  children: <TextSpan>[
    new TextSpan(text: 'Hello'),
    new TextSpan(text: 'World', style: new TextStyle(fontWeight: FontWeight.bold)),
  ],
),
);`

**Comment by xsahil03x** [comment]
Fixed in https://github.com/xsahil03x/giffy_dialog/releases/tag/v2.0.0
