### ISSUE TITLE
Issue: Botton overflowed by Xx pixels when Phone Display & Text Size bigger than normal

### ISSUE THREAD

**Issue by edwin-alvarez** [xsahil03x/giffy_dialog#68]
How to reproduce: Go to Setting > Accessibility > Display & Text Size > Larger Text > Larger Accessibility Sizes == ON
then make the text bigger and you will notice the issue:

![image](https://user-images.githubusercontent.com/5774873/80872751-d4a08b00-8c68-11ea-96fe-771b0fb466af.png)

**Comment by xsahil03x** [comment]
@edwin-alvarez you need to handle the text size based on your phone DPI.

**Comment by keremcankabadayi** [comment]
same issue. we should vertical scrollbar for `description`.

**Comment by jinfagang** [comment]
@keremcankabadayi How to add it?

**Comment by nayakastha** [comment]
You can 

> Same issue. It shouldn't matter how long the dialog text could be? Maybe we can show a scrollbar or make the dialog higher to prevent the overflow issue?

You can wrap the text with `SingleChildScrollView()`, I guess that will remove the error of text overflow.

**Comment by rody1983** [comment]
Same issue . Any one solve this problem

**Comment by xsahil03x** [comment]
Fixed in https://github.com/xsahil03x/giffy_dialog/releases/tag/v2.0.0
