### ISSUE TITLE
Lottie Support

### ISSUE THREAD

**Issue by safiullahahamed** [xsahil03x/giffy_dialog#71]
Will this support Lottie files?

https://pub.dev/packages/lottie

Thanks in advance!

**Comment by xsahil03x** [comment]
@safiullahahamed thanks, it currently does not support Lottie files but it's in my backlog.

**Comment by xsahil03x** [comment]
Fixed in https://github.com/xsahil03x/giffy_dialog/releases/tag/v2.0.0
