### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by dna-f** [xsahil03x/giffy_dialog#74]
Hi, is Null safety migration on roadmap?
Thanks

**Comment by Saad29** [comment]
Much needed feature, i hope #75 gets merged soon enough if everything is alright.

**Comment by xsahil03x** [comment]
Hey, i started migrating the package to null-safety. Will soon release the latest version.

**Comment by dna-f** [comment]
Hi! Any news?

**Comment by mdat31** [comment]
i needed it two

**Comment by sinnky** [comment]
my project need this package!! when will you update this package?

**Comment by jpetro416** [comment]
I need this as well!

**Comment by bytelyus** [comment]
and we need it now...

**Comment by markbulingit** [comment]
HEy!!!!!!! Release the Null Safety!!!!!!

**Comment by iqfareez** [comment]
please release null safety 😞

**Comment by DaemonChoejur** [comment]
Any updates on null safety release?

**Comment by liudonghua123** [comment]
Any updates on null safety release?

**Comment by xsahil03x** [comment]
Fixed in https://github.com/xsahil03x/giffy_dialog/releases/tag/v2.0.0
