### ISSUE TITLE
Is their a list of publicly available flare animations?

### ISSUE THREAD

**Issue by zaidkazi** [xsahil03x/giffy_dialog#77]
I don't have the experience to develop great animations is their a list of free animations available anywhere?

**Comment by DavidSmekal** [comment]
On Rive's official site they have a place where you can browse. Just check what type of license is attached to it. A lot of them are CC BY 4.0 meaning you can use them in your own work as long as you give credit to the original author.

https://flare.rive.app/explore/popular/trending/all

**Comment by xsahil03x** [comment]
Fixed in https://github.com/xsahil03x/giffy_dialog/releases/tag/v2.0.0
