### ISSUE TITLE
Bottom Overflow in Landscape Mode

### ISSUE THREAD

**Issue by Purus** [xsahil03x/giffy_dialog#8]
When the screen is in portrait mode, we get an error message of overflowing bottom pixels. This happens even in the sample app available.

**Comment by xsahil03x** [comment]
Yeah i know i am quite busy now a days due to office, if you want to fix this then go ahead.
Do it something like GIF on the left side and text on the right side of dialog.

**Comment by joaoaugustogrobe** [comment]
Hello! I'd like to work on it

**Comment by xsahil03x** [comment]
Hey, @joaoaugustogrobe yes go on.

**Comment by dpedrinha** [comment]
@joaoaugustogrobe it's done. But it seems to have some version or IDE incompatibilities. Maybe you can finish it. https://github.com/xsahil03x/giffy_dialog/pull/15

**Comment by imSanjaySoni** [comment]
> When the screen is in portrait mode, we get an error message of overflowing bottom pixels. This happens even in the sample app available.

Hey Purus can you clear the exact problem is in portrait or landscape mode, actually the title of issue and your comment are different.

**Comment by Purus** [comment]
I see the issue when in landscape mode. In my opinion, the view should be
responsive.

**Comment by madhukesh048** [comment]
I Have fixed this issue in this [PR](https://github.com/xsahil03x/giffy_dialog/pull/19)
