### ISSUE TITLE
Upgrade Flutter v2.5

### ISSUE THREAD

**Issue by ZoroRoronoaX** [xsahil03x/giffy_dialog#80]
Hi, I am trying to upgrade to the latest version in flutter and got this error. 

Because flare_loading 3.0.0 depends on flare_flutter ^3.0.0 and no versions of flare_loading match >3.0.0 <4.0.0, flare_loading ^3.0.0 requires flare_flutter ^3.0.0.
And because giffy_dialog >=1.8.0 depends on flare_flutter ^2.0.5, giffy_dialog >=1.8.0 is incompatible with flare_loading ^3.0.0.
And because flare_splash_screen 4.0.0 depends on flare_loading ^3.0.0 and no versions of flare_splash_screen match >4.0.0 <5.0.0, giffy_dialog >=1.8.0 is incompatible with flare_splash_screen ^4.0.0.
So, because accetera depends on both flare_splash_screen ^4.0.0 and giffy_dialog ^1.8.0, version solving failed.
pub get failed (1; So, because accetera depends on both flare_splash_screen ^4.0.0 and giffy_dialog ^1.8.0, version solving failed.)

**Comment by xsahil03x** [comment]
Fixed in https://github.com/xsahil03x/giffy_dialog/releases/tag/v2.0.0
