### ISSUE TITLE
bug: build error due deprecated usage of RaisedButton

### ISSUE THREAD

**Issue by ashuvssut** [xsahil03x/giffy_dialog#83]
Material You (Material v3) has [deprecated `RaisedButton` in favour of `ElevatedButton`](https://docs.flutter.dev/release/breaking-changes/buttons#context)

I am getting build errors due to the use of deprecated `RaisedButton`
```
/home/ashu/.pub-cache/hosted/pub.dev/giffy_dialog-1.8.0/lib/src/base_dialog.dart:203:13: Error: The method 'RaisedButton' isn't defined for the class '_BaseGiffyDialogState'.
- '_BaseGiffyDialogState' is from 'package:giffy_dialog/src/base_dialog.dart' ('/home/ashu/.pub-cache/hosted/pub.dev/giffy_dialog-1.8.0/lib/src/base_dialog.dart').
package:giffy_dialog/src/base_dialog.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'RaisedButton'.
            RaisedButton(
            ^^^^^^^^^^^^
/home/ashu/.pub-cache/hosted/pub.dev/giffy_dialog-1.8.0/lib/src/base_dialog.dart:217:13: Error: The method 'RaisedButton' isn't defined for the class '_BaseGiffyDialogState'.
- '_BaseGiffyDialogState' is from 'package:giffy_dialog/src/base_dialog.dart' ('/home/ashu/.pub-cache/hosted/pub.dev/giffy_dialog-1.8.0/lib/src/base_dialog.dart').
package:giffy_dialog/src/base_dialog.dart:1
Try correcting the name to the name of an existing method, or defining a method named 'RaisedButton'.
            RaisedButton(
            ^^^^^^^^^^^^
```

**Comment by birane012** [comment]
Hi Ashuvssut, i'm geting the same issue due to  the use of deprecated RaisedButton.

**Comment by ashuvssut** [comment]
You have to make these changes to fix your issue. 
https://github.com/xsahil03x/giffy_dialog/pull/84/files

its a temporary fix. Apply these changes only if you are the working sole developer on your app. 

Being from web dev background, another solution I know that works in nodejs projects is to directly put the link of the repository in package.json
Similary if you could somehow  put the link of my repo's (https://github.com/ashuvssut/giffy_dialog) `fix/deprecated-RaisedBtn` in pub.spec file to use it in your project inplace of using giffy_dialog package then things might work out. you have to google a bit if this is allowed in pub.spec file or not. I am not sure. 

I would suggest to use any other package form pub.dev cuz this package is getting outdated and its seems thats its not maintained anymore

**Comment by birane012** [comment]
I have done that first and when i was trying to make a pull request, i saw that you already do that. So i also a mail to the owner xdsahil@gmail.com and ask him to please merge your pull request.
Hopefully he saw the message.

**Comment by ashuvssut** [comment]
Since the PR is not getting reviewed, you can use the updated code in my repository
Add these lines to your `pubspec.yaml`
```
giffy_dialog: 
    git: 
      url: https://github.com/ashuvssut/giffy_dialog.git
      ref: master
```
This will be fixed. You can change back later (when my PR gets merged)

**Comment by birane012** [comment]
It's done.
Thanks!

**Comment by xsahil03x** [comment]
Fixed in https://github.com/xsahil03x/giffy_dialog/releases/tag/v2.0.0
